create table if not exists public.cadastros (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(trim(name)) between 2 and 80),
  email text not null check (char_length(email) between 3 and 120),
  car text check (car is null or char_length(car) <= 100),
  message text not null check (char_length(trim(message)) between 10 and 1000),
  consent boolean not null default false check (consent = true),
  source text not null default 'vertice-detail' check (source = 'vertice-detail'),
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.cadastros enable row level security;

grant usage on schema public to anon, authenticated;
grant insert on table public.cadastros to anon, authenticated;
grant usage, select on sequence public.cadastros_id_seq to anon, authenticated;

drop policy if exists "Allow contact form submissions" on public.cadastros;

create policy "Allow contact form submissions"
  on public.cadastros
  for insert
  to anon, authenticated
  with check (
    consent = true
    and source = 'vertice-detail'
  );